name:                Fasta-Region-Inspector
version:             0.1.0.0
github:              "Matthew-Mosior/Fasta-Region-Inspector"
license:             BSD3
author:              "Matthew C. Mosior"
maintainer:          "mattm.github@gmail.com"
copyright:           "BSD 3-Clause License"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Bioinformatics

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Matthew-Mosior/Fasta-Region-Inspector#readme>

dependencies:
- aeson 
- attoparsec
- base >= 4.7 && < 5
- bytestring-to-vector
- containers
- connection
- compact
- data-default 
- diagrams-lib 
- directory 
- deepseq 
- ghc-prof
- http-client
- http-client-tls
- http-types
- tls
- MissingH
- parallel
- parsec
- pcre-heavy 
- regex-compat
- regex-pcre
- regex-tdfa
- elynx-seq
- bytestring
- req
- sbv
- split
- stringsearch 
- massiv
- pipes-bytestring
- process
- raw-strings-qq
- retry
- temporary
- text 
- time
- transformers
- unordered-containers
- utf8-string
- vector 
- xml-conduit 
- xlsx 
- yaml 

library:
  source-dirs: src
  default-extensions:
   - MultiWayIf
   - DataKinds
   - DefaultSignatures
   - DeriveFoldable
   - DeriveFunctor
   - DeriveGeneric
   - DeriveTraversable
   - DerivingStrategies
   - DuplicateRecordFields
   - FlexibleContexts
   - FlexibleInstances
   - GADTs
   - GeneralizedNewtypeDeriving
   - InstanceSigs
   - LambdaCase
   - MagicHash
   - NamedFieldPuns
   - NoMonomorphismRestriction
   - NumDecimals
   - OverloadedStrings
   - PatternSynonyms
   - PolyKinds
   - QuantifiedConstraints
   - RankNTypes
   - RecordWildCards
   - RoleAnnotations
   - ScopedTypeVariables
   - StandaloneDeriving
   - Strict
   - TupleSections
   - TypeApplications
   - TypeFamilyDependencies
   - TypeOperators
   - TypeSynonymInstances
   - ViewPatterns
   - OverloadedLists
   - QuasiQuotes

executables:
   fasta-region-inspector-exe:
    main:                Main.hs
    source-dirs:         app
    default-extensions:
     - MultiWayIf
     - DataKinds
     - DefaultSignatures
     - DeriveFoldable
     - DeriveFunctor
     - DeriveGeneric
     - DeriveTraversable
     - DerivingStrategies
     - DuplicateRecordFields
     - FlexibleContexts
     - FlexibleInstances
     - GADTs
     - GeneralizedNewtypeDeriving
     - InstanceSigs
     - LambdaCase
     - MagicHash
     - NamedFieldPuns
     - NoMonomorphismRestriction
     - NumDecimals
     - OverloadedStrings
     - PatternSynonyms
     - PolyKinds
     - QuantifiedConstraints
     - RankNTypes
     - RecordWildCards
     - RoleAnnotations
     - ScopedTypeVariables
     - StandaloneDeriving
     - Strict
     - TupleSections
     - TypeApplications
     - TypeFamilyDependencies
     - TypeOperators
     - TypeSynonymInstances
     - ViewPatterns
     - OverloadedLists
     - QuasiQuotes
    ghc-options:
     - -threaded
     - -O2
     - -rtsopts
     - -with-rtsopts=-N
     - -with-rtsopts=-xn
     - -fllvm
    dependencies:
     - Fasta-Region-Inspector

tests:
  fasta-region-inspector-test:
    main:                Spec.hs
    source-dirs:         test
    default-extensions:
     - MultiWayIf
     - DataKinds
     - DefaultSignatures
     - DeriveFoldable
     - DeriveFunctor
     - DeriveGeneric
     - DeriveTraversable
     - DerivingStrategies
     - DuplicateRecordFields
     - FlexibleContexts
     - FlexibleInstances
     - GADTs
     - GeneralizedNewtypeDeriving
     - InstanceSigs
     - LambdaCase
     - MagicHash
     - NamedFieldPuns
     - NoMonomorphismRestriction
     - NumDecimals
     - OverloadedStrings
     - PatternSynonyms
     - PolyKinds
     - QuantifiedConstraints
     - RankNTypes
     - RecordWildCards
     - RoleAnnotations
     - ScopedTypeVariables
     - StandaloneDeriving
     - Strict
     - TupleSections
     - TypeApplications
     - TypeFamilyDependencies
     - TypeOperators
     - TypeSynonymInstances
     - ViewPatterns
     - OverloadedLists
     - QuasiQuotes
    ghc-options:
     - -threaded
     - -O2
     - -rtsopts
     - -with-rtsopts=-N
     - -with-rtsopts=-xn
     - -fllvm
    dependencies:
     - Fasta-Region-Inspector 
